### ISSUE TITLE
GraphQL?

### ISSUE THREAD

**Issue by edsu** [tmsss/gatsby-plugin-flexsearch#2]
Is there a way to use your plugin to index JSON data that is made available via GraphQL? Thanks for any assistance you can provide.

**Comment by tmsss** [comment]
Hi there, thank you for reaching out! Right now it only works with any nodes available, you just need to change the `type` in `gatsby-config.js`, e.g. from `'MarkdownRemark'` to whatever you want and it should work. 

I don't know if this helps, but if you post your code or provide further explanation about you want to accomplish maybe I can help you.

**Comment by edsu** [comment]
Well, I suppose I don't know exactly what I want yet, since I am just learning FlexSearch now. I was hoping to index particular fields in my JSON data, which I use to build out a bunch of pages. So for example I have thousands of records like this below that I would like to create indexes on title, creator.name, etc.

```json
  {
    "id": "cpb-aacip-500-zc7rsr2g",
    "naebId": "61-Sp.OECD4",
    "umdId": "1533",
    "seriesTitle": [
      "recBx5hagrFDyNOii"
    ],
    "title": "Partnership for progress, part 4",
    "broadcastDate": "1961-11-21",
    "mediaType": "Sound",
    "formatPlaybackSpead": "7 1/2",
    "unitsOfMeasaure": "ips",
    "physical": "1/4 inch audio tape",
    "duration": 870,
    "durationApproximate": "Yes",
    "seriesDescription": "This series, narrated by John F. Lewis, presents a report on the Organization for Economic Cooperation and Development (OECD).",
    "description": "This program continues to tell the story of the Organization for Economic Cooperation and Development and the context that surrounded it.",
    "priorityLevel": "Nominated/1st Priority",
    "location": "Hornbake Special Collections",
    "temporalCoverage": "1961-1970",
    "language": "English",
    "decade": "1960's",
    "year": "1961",
    "subject": [
      {
        "name": "Economic development.",
        "type": "Library of Congress Subject Authority Headings"
      }
    ],
    "creator": [
      {
        "name": "National Association of Educational Broadcasters",
        "role": "Producer"
      },
      {
        "name": "Lewis, John F.",
        "role": "Producer"
      }
    ],
    "contributor": [
      {
        "name": "Lewis, John F.",
        "role": "Narrator"
      },
      {
        "name": "Harbison, Frederick Harris",
        "role": "Speaker"
      },
      {
        "name": "Vasey, John",
        "role": "Speaker"
      }
    ],
    "dimensions": {
      "value": "5",
      "units": "inches"
    },
    "genre": [
      {
        "name": "Documentary",
        "authority": "PBCore"
      },
      {
        "name": "History",
        "authority": "PBCore"
      }
    ]
  }
```

**Comment by edsu** [comment]
Looking a bit more at FlexSearch it seems like I should probably be configuring the index myself. I think your plugin serves as a great model for how to integrate FlexSearch with Gatsby, but asking your plugin to accommodate what I want to do seems to be asking too much of your plugin. I'll close this for now, but of course feel free to re-open if you feel otherwise.

**Comment by edsu** [comment]
I'm sorry to reopen this, but you made it sound like it might be possible to just change `type` in `gatsby-config.js` to something and things will work?

Here's my gatsby project https://github.com/umd-mith/airwaves/tree/gatsby which I am just starting to play with. You can see that lots of pages are created in my `gatsby-node.js` based on data in `data/episodes.json`. I would like to index those documents with FlexSearch.

**Comment by tmsss** [comment]
I've pulled your project and it seems to me that you've already got it working. Can I close this issue?

**Comment by edsu** [comment]
Thanks for taking a look!

**Comment by xdebbie** [comment]
@edsu have you managed to implement the search function on your project using Flexsearch + pulling data from a GraphQL query? I'm struggling with it now, not sure what I'm doing wrong

**Comment by edsu** [comment]
@xdebbie Sadly I gave up on using flexsearch since the library had some sharp edges I didn't understand and it appeared to no longer be supported. I tried elasticlunr instead, which worked more predictably and seemed just as efficient as flexsearch, at least for my purposes.

**Comment by xdebbie** [comment]
@edsu Turns out I managed to make it work on my project using 'react-use-flexsearch' and 'gatsby-plugin-local-search', but good to know Elasticlunr is an alternative as well. Neither works well with my project though because I have over 20,000 data rows so the loading time is really slow, I'm now finding ways to optimise the speed of my search engine... What I did figure though, was that Algolia (https://www.algolia.com/pricing/) is faster than the other options, however the free plan gives you a limit of 10,000 entries only.... for smaller projects it's worth taking a look at it, its plugin is quite decent too.
