### ISSUE TITLE
Not able to return my node data

### ISSUE THREAD

**Issue by jerome281** [tmsss/gatsby-plugin-flexsearch#3]
I'm struggling returning my node data. Any suggestions?

![image](https://user-images.githubusercontent.com/6596071/61445420-46f7e700-a945-11e9-81c6-09714dcc658c.png)

Here my gatsby-config.js file setting
```
`options: {
        languages: ['en'],
        type: 'wpgraphql',
        fields: [
          {
            name: 'title',
            indexed: true,
            resolver: 'allJobs.nodes.title',
            attributes: {
              encode: 'balance',
              tokenize: 'strict',
              threshold: 6,
              depth: 3
            },
            store: true
          },
          {
            name: 'url',
            indexed: false,
            resolver: 'allJobs.nodes.uri',
            store: true
          }
        ]
      }`
```

**Comment by travis-r6s** [comment]
If you are still having issues - there are a couple of things wrong here:

`type: 'wpgraphql'` Should be the typename of 'Job' - if you add `__typename` to the nodes query in graphiql, you will see the typename. So it will look something like `type: 'Job'`.

Then the `resolver:` should be the fields in this type, so just `title` and `url` for instance - you don't need to add the path to it.

So for example, I have this query:

```graphql
query MyQuery {
  allProducts {
    nodes {
      title
      handle
    	__typename
    }
  }
}
```

Which gives the below data:

```json
{
  "data": {
    "allProducts": {
      "nodes": [
        {
          "title": "Apple Juice",
          "handle": "apple-juice",
          "__typename": "Product"
        },
...
```

And my flexsearch options looks like:
```javascript
const flexsearchOptions = {
  languages: ['en'],
  type: 'Product',
  fields: [
    {
      name: 'title',
      indexed: true,
      resolver: 'title',
      attributes: {
        encode: 'extra',
        tokenize: 'strict',
        threshold: 1,
        resolution: 9,
        depth: 4
      },
      store: true
    },
    {
      name: 'handle',
      indexed: false,
      resolver: 'handle',
      store: true
    },
...
```

**Comment by Richacinas** [comment]
Did this ever get resolved? I'm struggling as well to find a solution.. Trying all sorts of **type** and **resolver** combinations without success..
